name: Deploy

on:
  workflow_run:
    workflows: ["Lint", "Tests"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Forge Deployment
        env:
          FORGE_DEPLOY_URL: ${{ secrets.FORGE_DEPLOY_URL }}
        run: curl -X POST "$FORGE_DEPLOY_URL"
